### ISSUE TITLE
About the evaluation program

### ISSUE THREAD

**Issue by momo1986** [P2333/Bag-of-Tricks-for-AT#1]
Hello, Pang.

Thanks for your sharing.

Congratulations on your contributions to robustness research.

I tried to run you empirical engineering trick progrm in default setting and run the evalution program from you AT_With_He paper.
https://github.com/AnonymousForDoubleBlind/AT_with_HE/blob/master/CIFAR-10/pgd_attack_cifar10.py

However, it is very wierd that the PGD err is 0.85 while natural err is 0.81.

If I wnt to use the pgd_attack_cifar10.py, what other step should I do to fix the bug so that correct results can be demonstrated.

Thank & Regards!
Momo

**Comment by P2333** [comment]
Hi Momo, thank you for your appreciation.

We just add a new script [eval_cifar.py](https://github.com/P2333/Bag-of-Tricks-for-AT/blob/master/eval_cifar.py), which includes evaluation under PGD attacks (CE loss or CW loss) and AutoAttack. You can set the attacking parameters (e.g., attack_iters, restarts) as you need.
