### ISSUE TITLE
Some question

### ISSUE THREAD

**Issue by jiaxiaojunQAQ** [P2333/Bag-of-Tricks-for-AT#2]
In the original Trades, it uses the beta to trade the adv loss and clean loss. But  I did not find beta in the code?

**Comment by P2333** [comment]
This code mainly involves experiments on PGD-AT. You can simply modify the code to implement TRADES referring to [this draft](https://github.com/P2333/Rectified-Rejection/blob/4f63e428cdc97d673e7175915cd684e2d8232eab/train_cifar.py#L80).

**Comment by jiaxiaojunQAQ** [comment]
> This code mainly involves experiments on PGD-AT. You can simply modify the code to implement TRADES referring to [this draft](https://github.com/P2333/Rectified-Rejection/blob/4f63e428cdc97d673e7175915cd684e2d8232eab/train_cifar.py#L80).

OK, This means the provided code is used for PGD-AT, not for Trades. And we can run the Original Trades with weight-decay 5e-4 to get the model against AA 53.8% .  Moreover, whether is weight decay useful for all models? When I use the Resnet18 as the target model, the impact of weight-decay is very small.

**Comment by P2333** [comment]
Yes, you can only change the weight decay from 2e-4 to 5e-4 in the original TRADES code. You can refer to Figure 1(a) in our paper, larger models (e.g., WRN-34-10) will be more significantly affected by weight decay.

**Comment by jiaxiaojunQAQ** [comment]
> Yes, you can only change the weight decay from 2e-4 to 5e-4 in the original TRADES code. You can refer to Figure 1(a) in our paper, larger models (e.g., WRN-34-10) will be more significantly affected by weight decay.

Thank you for the reply
