### ISSUE TITLE
Provided Checkpoints inaccurate result

### ISSUE THREAD

**Issue by benningtonlee7** [P2333/Bag-of-Tricks-for-AT#4]
Hi! I tested the provided checkpoints on both WRN-34-20 and WRN-34-10 and did not get the same results as the paper. Both are around 60+%. Are they the right checkpoints? Thanks!

**Comment by P2333** [comment]
Hi, did you use the provided [eval_cifar.py](https://github.com/P2333/Bag-of-Tricks-for-AT/blob/master/eval_cifar.py) script for test?

**Comment by benningtonlee7** [comment]
Thanks for the reply! Yep, I did! I created the following for WRN-34-20 with [chekpoint](http://ml.cs.tsinghua.edu.cn/~xiaoyang/downloads/bag_of_tricks/wide20_trades_eps8_tricks.pt)

`model_test = WideResNet(34, 10, widen_factor=20, dropRate=0.0).cuda() # WRN-34-20`
and 
`model_test = WideResNet(34, 10, widen_factor=10, dropRate=0.0).cuda() # WRN-34-10` with [chekpoint](http://ml.cs.tsinghua.edu.cn/~xiaoyang/downloads/bag_of_tricks/wide10_trades_eps8_tricks.pt)

**Comment by P2333** [comment]
Hi, I have check the scripts, and recall that the checkpoints provided for TRADES do not use input normalization. So you just need to remove the normalize function and directly feed input into the model in [utils_plus.py](https://github.com/P2333/Bag-of-Tricks-for-AT/blob/314683adcfe9ea7c7bfbff50007da510b21f56e1/utils_plus.py#L124). Similarly when evaluating PGD, the normalize function should also be removed for TRADES checkpoints.

Sorry for the inconvenience.

**Comment by benningtonlee7** [comment]
Thanks! Now I do see that the accuracy is as expected.
