### ISSUE TITLE
Does dataset nomalization matter in Adversarial Training?

### ISSUE THREAD

**Issue by yljblues** [P2333/Bag-of-Tricks-for-AT#7]
Have you tried adversarial training without dataset normalization, which means *Input <- (Input - mean) / std*?

I tried TRADES on CIFAR10 without dataset normalization, and couldn't get a comparable result.

So I wonder if dataset normalization is the problem.

**Comment by P2333** [comment]
It seems that the official implementation of TRADES did not apply dataset normalization (https://github.com/yaodongyu/TRADES/blob/master/trades.py#L75), where the input is clamp between [0,1], not between [-mean/std, (1-mean)/std]
